# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      ['ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-amd64']
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/biohackerellie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/biohackerellie/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      ['ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-arm64v8']
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/biohackerellie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/biohackerellie/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/biohackerellie/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/biohackerellie/{{ .ProjectName }}:{{ .Version }}-arm64v8
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: '{{ incpatch .Version }}-SNAPSHOT'
source:
  # https://goreleaser.com/customization/source/
  enabled: true
